### ISSUE TITLE
Hope you are well

### ISSUE THREAD

**Issue by staticdev** [geerlingguy/geerlingguy#2]
I saw this study and remembered you.. maybe some hope?

https://medicalxpress.com/news/2022-08-insights-mechanisms-crohn-disease-potential.html

Take care!

**Comment by geerlingguy** [comment]
Thanks! And yes, I've seen a little bit of that research in the past—it's definitely in the 'far future' state in terms of patient trials and new drugs, but there are also a few other encouraging areas of research that my doc (a researcher at Washington University Med School in St. Louis) has been following. We'll see how things pan out... I'm hopeful!

Thanks :)
